### PR TITLE
Non-modal dialog

### PR DESCRIPTION
**Pull request by khonkhortisan**
Fixes https://github.com/ThoreBor/Anki_Leaderboard/issues/7
You can do reviews while glaring at the person in the slot above you!
Still requires the user to select Leaderboard→Leaderboard in order to update the display.
Keeps a reference to the dialog, preventing it from being garbage-collected immediately as Main() finishes.
Re-positions the window and switches back to the default tab when re-opened, because setupUi starts from scratch.

### CODE REVIEW

**Comment by ThoreBor** [comment]
Great, I'll work on #8 and #9

**Comment by ThoreBor** [comment]
I had to undo the changes, because when first opening Anki the leaderboard would immediately minimize.

**Comment by khonkhortisan** [comment]
Are you sure it's not going behind the Anki window? The browser would do this for me before, so I didn't think anything of it.  This is the behavior I'm seeing:
If Anki was the only window selected between two openings of leaderboard (open leaderboard close leaderboard open leaderboard), the leaderboard will open in front of anki.
If another window was selected between two openings of leaderboard (open leaderboard close leaderboard select other window select Anki window open leaderboard), the leaderboard will open behind anki.
So something (the window manager?) is remembering past window activation states, maybe changing some flag will fix it? I'm on windows 10, if you're on something else (or have different focus-stealing rules?) maybe it is minimizing for you. If it was released this way I'd make a separate issue for it, but as it's reverted I guess this is the proper place for this. If it really is minimizing for you, does changing Leaderboard.py:16 `dialog.setWindowFlags(QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowMinimizeButtonHint)` to `dialog.setWindowFlags(QtCore.Qt.Dialog)` (so there's no minimize button) stop it from minimizing?

**Comment by khonkhortisan** [comment]
Does this code work for you? it seems to work for me. If I select another window while it's loading the leaderboard, the stack will be from bottom to top anki, leaderboard, other window.
```py
		mw.leaderboard = start_main()
		mw.leaderboard.show()
		mw.leaderboard.raise_()
		mw.leaderboard.activateWindow()
```
based on https://stackoverflow.com/questions/12118939/how-to-make-a-pyqt4-window-jump-to-the-front

**Comment by khonkhortisan** [comment]
If I close another window while the leaderboard is loading, it opens behind anki. I don't get this at all.

**Comment by ThoreBor** [comment]
> ```python
> mw.leaderboard = start_main()
> mw.leaderboard.show()
> mw.leaderboard.raise_()
> mw.leaderboard.activateWindow()
> ```

This works for me, thanks!

**Pull request merged**
