### PR TITLE
Improve efficiency of statistical calculations

### PR DESCRIPTION
**Pull request by SmallFluffyIPA**
Hey, 

saw the discussion about sluggishness. While the network communication probably causes most of that, the way Stats.py calculated things wasn't particular efficient and might as well have added to that to that negative user experience. 

So here we are. Do review carefully though, I'm not sure whether the league_ functions at the end have a off by one day error with the end_day or not. 

SmallFluffyIPA

### CODE REVIEW

**Comment by ThoreBor** [comment]
Hi, thank you very much. This is great! My version wasn't nearly as fast and pretty as yours. I do have a question, though.
In `reviews_past_31_days` you wrote:
```
if time_now < new_day:
    end_day = datetime.datetime.combine(date.today() + timedelta(days=1), new_day)
else:
    end_day = datetime.datetime.combine(date.today() + timedelta(days=2), new_day)
```
But I think it should be:
```
if time_now < new_day:
    end_day = datetime.datetime.combine(date.today(), new_day)
else:
    end_day = datetime.datetime.combine(date.today() + timedelta(days=1), new_day)
```
Or am I missing something? If my next day starts at 4 am and it's currently 9 pm, end_day should be the next day at 4 am. Both work though, because I didn't do any reviews two days from now.

The league functions look fine to me. I'll do some more tests though. 
Again, thanks a lot!

**Comment by SmallFluffyIPA** [comment]
You're right about review_past_31_days. That wasn't right at all. I also reworked the streak calculation as it wasn't considering some not so uncommon cases.

**Comment by ThoreBor** [comment]
The new streak function doesn't work for me. It returns a much shorter streak than I actually have. I don't really understand why you made the additional changes. I think the previous commit worked just fine and looking at the hours is not necessary.

Here's my thought process. Let me know where I'm wrong:

When reviewing a card, the time gets stored in the database in unix-milliseconds. The start of the next day doesn't matter. So converting these timestamps to dates and checking how many consecutive dates there are should be enough when the start of the next day is at 0 am, or when there are no reviews between 0 am and the start of the next day.
The problem is  if there are (only) reviews in this timeframe. The date should be the date - 1 day in this case. So this:
`mw.col.db.list("SELECT DISTINCT strftime('%Y-%m-%d', datetime((id-?) / 1000, 'unixepoch')) FROM revlog ORDER BY id DESC;", new_day_shift_in_ms)` should return all the correct Anki dates.  Because if I'm doing reviews at 2am it would subtract 4 hours from the timestamp, making it the date of yesterday.

**Comment by SmallFluffyIPA** [comment]
I just now saw your comment, for some reason I didn't got a notification. The reason for the change is pretty simple. I kinda forgot that I solved that problem, so I just went a head and solved in a different, more convoluted way, again. Turns out two rights, make a wrong.

**Comment by ThoreBor** [comment]
Haha, okay. Looks good now. Thank you again!

**Pull request merged**
