### PR TITLE
Allow easier selection of menu items using the keyboard

### PR DESCRIPTION
**Pull request by zjosua**

### CODE REVIEW

**Comment by ThoreBor** [comment]
What exactly does this do? I don't notice a difference.

**Comment by zjosua** [comment]
image
You can select the options by pressing the key corresponding to the underlined letters.

**Comment by ThoreBor** [comment]
That's what i thought, but it doesn't work for me. In fact it removes the other shortcuts from the toolbar. 
image

**Comment by ThoreBor** [comment]
It works now, after syncing Anki for some reason, but when I first open Anki it looks like in the screenshot above.

**Pull request merged**
